processes:
  - id: zip_file_matcher
    implementation: Geopilot.Pipeline.Processes.Matcher.FileMatcher.FileMatcherProcess
    default_config:
      fileExtensions:
        - zip
  - id: unzipper
    implementation: Geopilot.Pipeline.Processes.Unzip.UnzipProcess
  - id: vsa_matcher
    implementation: VsaCheckerAnalytics.Processors.VsaMatcher.VsaMatcherProcess
  - id: geopackage_generation
    implementation: VsaCheckerAnalytics.Processors.GeopackageGeneration.GeopackageGenerationProcess
  - id: network_topology_patcher
    implementation: VsaCheckerAnalytics.Processors.NetworkTopologyPatcher.NetworkTopologyPatcherProcess
  - id: error_overview_export
    implementation: VsaCheckerAnalytics.Processors.ErrorOverviewExport.ErrorOverviewExportProcess
    default_config:
      errorDataSheet: "Error Data"
      errorDataAttributeMapping:
        recommendation_detail: Recommendation Detail
        recommendation: Recommendation
        gsp: GEP
        uc: WK
        module: Modul
        model: Modell
        category: Kategorie
        status: Status
        owner: Eigentümer
        function_hierarchic: Funktionhierarchisch
        detail: Detail
        error: Fehlertyp
        errorid: Fehler-ID
        class: Klasse
        topic: Thema
        check_type: Prüftyp
        tid: TID
        fid: FID
      errorDataColumnMapping:
        recommendation_detail: A
        recommendation: B
        gsp: C
        uc: D
        module: E
        model: F
        category: G
        status: H
        owner: I
        function_hierarchic: J
        detail: K
        error: L
        errorid: M
        class: N
        topic: O
        check_type: P
        tid: Q
        fid: R
      errorObjectSheet: "Error Object"
      errorObjectAttributeMapping:
        gsp_max: GEP Maximum
        uc_max: WK Maximum
        count_error: Anzahl Fehler
        class: Klasse
        tid: TID
        fid: FID
      errorObjectColumnMapping:
        gsp_max: A
        uc_max: B
        count_error: C
        class: D
        tid: E
        fid: F
      overviewWkSheet: "Uebersicht WK"
      overviewGepSheet: "Uebersicht GEP"
      overviewRowFields:
        - "class"
        - "error"
      overviewFilterFields:
        - "check_type"
        - "function_hierarchic"
        - "owner"
        - "status"
      overviewValueField: "fid"
      overviewValueName: "Anzahl Fehler"
      cantonErrorObjectSheet: "raw_data"
      cantonErrorColumnMapping:
        tabelle: A
        attribut: B
        anzahl_total: C
        anzahl_paa: D
        anzahl_saa: E
        anzahl_null: F
        anzahl_null_paa: G
        anzahl_null_saa: H
pipelines:
  - id: vsa_checker_analytics
    display_name:
      de: VSA Checker Analytics
      en: VSA Checker Analytics
      fr: VSA Checker Analytics
      it: VSA Checker Analytics
    steps:
      - id: gep_checker_file_matcher
        display_name:
          de: GEP-Datachecker Resultate identifizieren (ZIP)
          en: Identify GEP-Datachecker results (ZIP)
          fr: Identifier les GEP-Datachecker résultats (ZIP)
          it: Identificare i GEP-Datachecker resultati (ZIP)
        process_id: zip_file_matcher
        input:
          files: "${upload()}"
        output_actions:
          - property: StatusMessage
            actions:
              - StatusMessage
        conditions:
          post:
            fail_conditions:
              - expression: "Length([gep_checker_file_matcher.MatchedFiles]) != 1"
                message:
                  de: "Genau ein GEP-Datachecker Resultatordner ist erforderlich"
                  en: "Exactly one GEP Data Checker results folder is required"
                  fr: "Un seul dossier de résultats GEP-Datachecker est nécessaire"
                  it: "È necessaria esattamente una cartella dei risultati di GEP-Datachecker"
      - id: gep_checker_unzipper
        display_name:
          de: GEP-Datachecker Resultate entpacken
          en: Unzip GEP-Datachecker results
          fr: Décompresser les fichiers GEP-Datachecker
          it: Decomprimere dei file GEP-Datachecker
        process_id: unzipper
        input:
          zipFile: "${step_output(gep_checker_file_matcher.MatchedFiles)}"
        output_actions:
          - property: StatusMessage
            actions:
              - StatusMessage
      - id: vsa_matcher
        display_name:
          de: Identifizieren der Transferdatei und Logfiles
          en: Identifying the transfer file and log files
          fr: Identification du fichier de transfert et des fichiers logs
          it: Identificazione del file di trasferimento e dei file di log
        process_id: vsa_matcher
        input:
          files: "${upload()}"
          unzippedFiles: "${step_output(gep_checker_unzipper.ExtractedFiles)}"
        output_actions:
          - property: StatusMessage
            actions:
              - StatusMessage
        conditions:
          post:
            fail_conditions:
              - expression: "Length([vsa_matcher.Gep]) != 1"
                message:
                  de: "Genau eine Transferdatei (XTF) erlaubt"
                  en: "Exactly one transfer file (XTF) is needed"
                  fr: "Un seul fichier de transfert (XTF) est requis"
                  it: "È richiesto esattamente un file di trasferimento (XTF)"
              - expression: "Length([vsa_matcher.UserOrgTable]) > 1"
                message:
                  de: "Mehrere benutzerdefinierte Organisationstabellen gefunden"
                  en: "Multiple user-defined organisation tables found"
                  fr: "Plusieurs tables d'organisation personnalisées ont été détectées"
                  it: "Sono state trovate diverse tabelle organizzative personalizzate"
              - expression: "Length([vsa_matcher.CheckerCsvA]) != 1"
                message:
                  de: "Es ist eine CSV-Logdatei für die Pflichtattribute ARA-Einzugsgebiet (A) notwendig"
                  en: "A log file is required for error types A (CSV)"
                  fr: "Un fichier log CSV pour les attributs obligatoires Bassin versant STEP (A) nécessaire"
                  it: "Per i tipi di errore A è necessario un file di log (CSV)"
              - expression: "Length([vsa_matcher.CheckerCsvFp]) != 1"
                message:
                  de: "Es ist eine CSV-Logdatei der Fachprüfungen (FP) notwendig"
                  en: "A log file is required for error types FP (CSV)"
                  fr: "Un fichier log CSV pour les Examens professionnels (FP) nécessaire"
                  it: "Per i tipi di errore FP è necessario un file di log (CSV)"
              - expression: "Length([vsa_matcher.CheckerCsvT]) != 1"
                message:
                  de: "Es ist eine CSV-Logdatei für die Pflichtattribute Trägerschaft (T) notwendig"
                  en: "A log file is required for error types T (CSV)"
                  fr: "Un fichier log CSV pour les attributs obligatoires autorité responsable (T) nécessaire"
                  it: "Per i tipi di errore T è necessario un file di log (CSV)"
              - expression: "[vsa_matcher.GpkgTemplate] == null && Length([vsa_matcher.Gep]) == 1 && Length([vsa_matcher.UserOrgTable]) == 1 && Length([vsa_matcher.CheckerCsvA]) == 1 && Length([vsa_matcher.CheckerCsvFp]) == 1 && Length([vsa_matcher.CheckerCsvT]) == 1"
                message:
                  de: "Bitte wenden Sie sich an den Administrator (GPKG Vorlage fehlt)"
                  en: "Please contact the administrator (GPKG template missing)"
                  fr: "Veuillez contacter l'administrateur (modèle GPKG manquant)"
                  it: "Si prega di rivolgersi all'amministratore (manca il modello GPKG)"
              - expression: "[vsa_matcher.StandardOrgTable] == null  && Length([vsa_matcher.Gep]) == 1 && Length([vsa_matcher.UserOrgTable]) == 1 && Length([vsa_matcher.CheckerCsvA]) == 1 && Length([vsa_matcher.CheckerCsvFp]) == 1 && Length([vsa_matcher.CheckerCsvT]) == 1"
                message:
                  de: "Bitte wenden Sie sich an den Administrator (Organisations-Tabelle kann nicht heruntergeladen werden)"
                  en: "Please contact the administrator (organization table cannot be downloaded)"
                  fr: "Veuillez contacter l'administrateur (Impossible de télécharger la table d'organisation)"
                  it: "Si prega di rivolgersi all'amministratore (Non è possibile scaricare la tabella organizzativa)"
      - id: geopackage_generation
        display_name:
          de: Daten importieren und aufbereiten
          en: Import and prepare data
          fr: Importer et traiter les données
          it: Importazione ed elaborazione dei dati
        process_id: geopackage_generation
        input:
          geoPackage: "${step_output(vsa_matcher.GpkgTemplate)}"
          dssMiniXtf: "${step_output(vsa_matcher.Gep)}"
          defaultOrgsXtf: "${step_output(vsa_matcher.StandardOrgTable)}"
          userOrgsXtf: "${step_output(vsa_matcher.UserOrgTable)}"
          checkerCsvT: "${step_output(vsa_matcher.CheckerCsvT)}"
          checkerCsvA: "${step_output(vsa_matcher.CheckerCsvA)}"
          checkerCsvFp: "${step_output(vsa_matcher.CheckerCsvFp)}"
          errorMatrix: "${file(errorMatrix.xlsx)}"
          language: "${step_output(vsa_matcher.Language)}"
          modelVersion: "${step_output(vsa_matcher.ModelVersion)}"
        output_actions:
          - property: StatusMessage
            actions:
              - StatusMessage
        conditions:
          post:
            fail_conditions:
              - expression: "[geopackage_generation.GeneratedGeopackage] == null"
                message:
                  de: "Der Import der Daten in die Vorlagedatei ist fehlgeschlagen"
                  en: "The import of the data into the GeoPackage has failed"
                  fr: "L'importation des données dans le GeoPackage a échoué"
                  it: "L'importazione dei dati nel GeoPackage non è riuscita"
      - id: error_overview_export_de
        display_name:
          de: Fehler aggregieren und exportieren (DE)
          en: Aggregate and export errors (DE)
          fr: Regrouper et exporter les erreurs (DE)
          it: Aggregare ed esportare gli errori (DE)
        process_id: error_overview_export
        conditions:
          pre:
            skip_conditions:
              - expression: "[vsa_matcher.Language] != 'DE'"
                message:
                  de: "Dieser Schritt wird nur für deutsche Modelle ausgeführt"
                  en: "This step applies only to German models"
                  it: "Cette étape ne concerne que les modèles allemands"
                  fr: "Questa operazione viene eseguita solo sui modelli tedeschi"
        input:
          geopackage: "${step_output(geopackage_generation.GeneratedGeopackage)}"
          cantonErrorMatrixTemplate: "${file(errorMatrixKanton_de.xlsx)}"
        output_actions:
          - property: ErrorOverview
            actions:
              - Download
          - property: CantonErrorMatrix
            actions:
              - Download
          - property: StatusMessage
            actions:
              - StatusMessage
      - id: error_overview_export_fr
        display_name:
          de: Fehler aggregieren und exportieren (FR)
          en: Aggregate and export errors (FR)
          fr: Regrouper et exporter les erreurs (FR)
          it: Aggregare ed esportare gli errori (FR)
        process_id: error_overview_export
        conditions:
          pre:
            skip_conditions:
              - expression: "[vsa_matcher.Language] != 'FR'"
                message:
                  de: "Dieser Schritt wird nur für französische Modelle ausgeführt"
                  en: "This step applies only to French models"
                  it: "Cette étape ne concerne que les modèles français"
                  fr: "Questa operazione viene eseguita solo sui modelli francesi"
        input:
          geopackage: "${step_output(geopackage_generation.GeneratedGeopackage)}"
          cantonErrorMatrixTemplate: "${file(errorMatrixKanton_fr.xlsx)}"
        output_actions:
          - property: ErrorOverview
            actions:
              - Download
          - property: CantonErrorMatrix
            actions:
              - Download
          - property: StatusMessage
            actions:
              - StatusMessage
      - id: network_topology_patcher
        display_name:
          de: Netzwerktopologie ergänzen
          en: Network Topology completion
          fr: Finalisation de la topologie du réseau
          it: Completamento della topologia di rete
        process_id: network_topology_patcher
        input:
          geoPackage: "${step_output(geopackage_generation.GeneratedGeopackage)}"
        output_actions:
          - property: PatchedGeopackage
            actions:
              - Download
          - property: StatusMessage
            actions:
              - StatusMessage
        conditions:
          post:
            fail_conditions:
              - expression: "[network_topology_patcher.PatchedGeopackage] == null"
                message:
                  de: "Die Rekonstruktion der Netzwerktopologie ist fehlgeschlagen"
                  en: "Network topology reconstruction failed"
                  fr: "La reconstruction de la topologie du réseau a échoué"
                  it: "La ricostruzione della topologia di rete non è riuscita"
