<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>VsaCheckerAnalytics</RootNamespace>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="VSACheckerAnalytics.Test" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="EmbeddedResources\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="GeoWerkstatt.Geopilot.PipelineCore" Version="1.2.0-preview.324">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.7" />
    <PackageReference Include="NetTopologySuite" Version="2.6.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
